[hello@balazs4.de]
source            = imaps://hello%40balazs4.de@mail.your-server.de
source-cred-cmd   = pass hello@balazs4.de
outgoing          = smtps://hello%40balazs4.de@mail.your-server.de
outgoing-cred-cmd = pass hello@balazs4.de
default           = INBOX
from              = Balazs Varga <hello@balazs4.de>
copy-to           = INBOX.Sent
cache-headers     = true

[code@balazs4.de]
source            = imaps://code%40balazs4.de@mail.your-server.de
source-cred-cmd   = pass code@balazs4.de
outgoing          = smtps://code%40balazs4.de@mail.your-server.de
outgoing-cred-cmd = pass code@balazs4.de
default           = INBOX
from              = balazs4 <code@balazs4.de>
copy-to           = INBOX.Sent
cache-headers     = true

