[general]
use-terminal-pinentry = false
defaul-menu-cmd       = fzf

[compose]
edit-headers = true # turn it to false if you use address book

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=! html
.headers=colorize
