[window]
opacity = 1.00
decorations = "None"
dynamic_title = true
title = "alacritty"
class = { general = "alacritty", instance = "alacritty" }

[colors.primary]
background = "0x{{base00-hex}}"
foreground = "0x{{base05-hex}}"

[colors.cursor]
cursor = "0x{{base09-hex}}"
text = "0x{{base00-hex}}"

[colors.normal]
black = "0x{{base00-hex}}"
blue = "0x{{base0D-hex}}"
cyan = "0x{{base0C-hex}}"
green = "0x{{base0B-hex}}"
magenta = "0x{{base0E-hex}}"
red = "0x{{base08-hex}}"
white = "0x{{base05-hex}}"
yellow = "0x{{base0A-hex}}"

[colors.bright]
black = "0x{{base03-hex}}"
blue = "0x{{base0D-hex}}"
cyan = "0x{{base0C-hex}}"
green = "0x{{base0B-hex}}"
magenta = "0x{{base0E-hex}}"
red = "0x{{base08-hex}}"
white = "0x{{base07-hex}}"
yellow = "0x{{base0A-hex}}"

[colors]
indexed_colors = [
  { index = 16, color = "0x{{base09-hex}}" },
  { index = 17, color = "0x{{base0F-hex}}" },
  { index = 18, color = "0x{{base01-hex}}" },
  { index = 19, color = "0x{{base02-hex}}" },
  { index = 20, color = "0x{{base04-hex}}" },
  { index = 21, color = "0x{{base06-hex}}" },
]

[font]
normal = { family = "Geist Mono", style = "Medium" }
#carbon size = 11.0
#mcbpro size = 14.0

[keyboard]
bindings = [
  { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
  { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
  { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
  { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
  { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
  { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
  { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
  { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
  { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
  { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
]
