# https://raw.githubusercontent.com/aarowill/base16-alacritty/master/colors/base16-brewer-256.yml
# Base16 Brewer 256 - alacritty color config
# Timothée Poisot (http://github.com/tpoisot)
colors:
  # Default colors
  primary:
    background: '0x0c0d0e'
    foreground: '0xb7b8b9'

  cursor:
    cursor: '0xf81ce5'

  # Normal colors
  normal:
    black:   '0x0c0d0e'
    red:     '0xe31a1c'
    green:   '0x31a354'
    yellow:  '0xdca060'
    blue:    '0x3182bd'
    magenta: '0x756bb1'
    cyan:    '0x80b1d3'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x737475'
    red:     '0xe31a1c'
    green:   '0x31a354'
    yellow:  '0xdca060'
    blue:    '0x3182bd'
    magenta: '0x756bb1'
    cyan:    '0x80b1d3'
    white:   '0xfcfdfe'

# https://raw.githubusercontent.com/eendroroy/alacritty-theme/master/themes/solarized_light.yaml
# Colors (Solarized Light)
#light colors:
#light   primary:
#light     background: '0xfdf6e3'
#light     foreground: '0x586e75'
#light 
#light   cursor:
#light     cursor: '0xf81ce5'
#light 
#light   normal:
#light     black:   '0x073642'
#light     red:     '0xdc322f'
#light     green:   '0x859900'
#light     yellow:  '0xb58900'
#light     blue:    '0x268bd2'
#light     magenta: '0xd33682'
#light     cyan:    '0x2aa198'
#light     white:   '0xeee8d5'
#light 
#light   bright:
#light     black:   '0x002b36'
#light     red:     '0xcb4b16'
#light     green:   '0x586e75'
#light     yellow:  '0x657b83'
#light     blue:    '0x839496'
#light     magenta: '0x6c71c4'
#light     cyan:    '0x93a1a1'
#light     white:   '0xfdf6e3'

## custom
font:
  normal:
    family: Source Code Pro 
#carbon   size: 8.0
#vmware   size: 11.0
