[window]
decorations = "None"
dynamic_title = true
title = "alacritty"
class = { general = "alacritty", instance = "alacritty" }

[colors.primary]
background = "0x{{base00-hex}}"
foreground = "0x{{base05-hex}}"

[colors.cursor]
cursor = "0x{{base09-hex}}"
text = "0x{{base00-hex}}"

[colors.normal]
black = "0x{{base00-hex}}"
blue = "0x{{base0D-hex}}"
cyan = "0x{{base0C-hex}}"
green = "0x{{base0B-hex}}"
magenta = "0x{{base0E-hex}}"
red = "0x{{base08-hex}}"
white = "0x{{base05-hex}}"
yellow = "0x{{base0A-hex}}"

[colors.bright]
black = "0x{{base03-hex}}"
blue = "0x{{base0D-hex}}"
cyan = "0x{{base0C-hex}}"
green = "0x{{base0B-hex}}"
magenta = "0x{{base0E-hex}}"
red = "0x{{base08-hex}}"
white = "0x{{base07-hex}}"
yellow = "0x{{base0A-hex}}"

[colors]
indexed_colors = [
  { index = 16, color = "0x{{base09-hex}}" },
  { index = 17, color = "0x{{base0F-hex}}" },
  { index = 18, color = "0x{{base01-hex}}" },
  { index = 19, color = "0x{{base02-hex}}" },
  { index = 20, color = "0x{{base04-hex}}" },
  { index = 21, color = "0x{{base06-hex}}" },
]

[font]
normal = { family = "Geist Mono", style = "Medium" }
#carbon size = 11.0
#mcbpro size = 14.0

#mcbpro [keyboard]
#mcbpro bindings = [
#mcbpro   { key = "A",         mods = "Alt",       chars = "\u001ba" },
#mcbpro   { key = "B",         mods = "Alt",       chars = "\u001bb" },
#mcbpro   { key = "C",         mods = "Alt",       chars = "\u001bc" },
#mcbpro   { key = "D",         mods = "Alt",       chars = "\u001bd" },
#mcbpro   { key = "E",         mods = "Alt",       chars = "\u001be" },
#mcbpro   { key = "F",         mods = "Alt",       chars = "\u001bf" },
#mcbpro   { key = "G",         mods = "Alt",       chars = "\u001bg" },
#mcbpro   { key = "H",         mods = "Alt",       chars = "\u001bh" },
#mcbpro   { key = "I",         mods = "Alt",       chars = "\u001bi" },
#mcbpro   { key = "J",         mods = "Alt",       chars = "\u001bj" },
#mcbpro   { key = "K",         mods = "Alt",       chars = "\u001bk" },
#mcbpro   { key = "L",         mods = "Alt",       chars = "\u001bl" },
#mcbpro   { key = "M",         mods = "Alt",       chars = "\u001bm" },
#mcbpro   { key = "N",         mods = "Alt",       chars = "\u001bn" },
#mcbpro   { key = "O",         mods = "Alt",       chars = "\u001bo" },
#mcbpro   { key = "P",         mods = "Alt",       chars = "\u001bp" },
#mcbpro   { key = "Q",         mods = "Alt",       chars = "\u001bq" },
#mcbpro   { key = "R",         mods = "Alt",       chars = "\u001br" },
#mcbpro   { key = "S",         mods = "Alt",       chars = "\u001bs" },
#mcbpro   { key = "T",         mods = "Alt",       chars = "\u001bt" },
#mcbpro   { key = "U",         mods = "Alt",       chars = "\u001bu" },
#mcbpro   { key = "V",         mods = "Alt",       chars = "\u001bv" },
#mcbpro   { key = "W",         mods = "Alt",       chars = "\u001bw" },
#mcbpro   { key = "X",         mods = "Alt",       chars = "\u001bx" },
#mcbpro   { key = "Y",         mods = "Alt",       chars = "\u001by" },
#mcbpro   { key = "Z",         mods = "Alt",       chars = "\u001bz" },
#mcbpro   { key = "A",         mods = "Alt|Shift", chars = "\u001bA" },
#mcbpro   { key = "B",         mods = "Alt|Shift", chars = "\u001bB" },
#mcbpro   { key = "C",         mods = "Alt|Shift", chars = "\u001bC" },
#mcbpro   { key = "D",         mods = "Alt|Shift", chars = "\u001bD" },
#mcbpro   { key = "E",         mods = "Alt|Shift", chars = "\u001bE" },
#mcbpro   { key = "F",         mods = "Alt|Shift", chars = "\u001bF" },
#mcbpro   { key = "G",         mods = "Alt|Shift", chars = "\u001bG" },
#mcbpro   { key = "H",         mods = "Alt|Shift", chars = "\u001bH" },
#mcbpro   { key = "I",         mods = "Alt|Shift", chars = "\u001bI" },
#mcbpro   { key = "J",         mods = "Alt|Shift", chars = "\u001bJ" },
#mcbpro   { key = "K",         mods = "Alt|Shift", chars = "\u001bK" },
#mcbpro   { key = "L",         mods = "Alt|Shift", chars = "\u001bL" },
#mcbpro   { key = "M",         mods = "Alt|Shift", chars = "\u001bM" },
#mcbpro   { key = "N",         mods = "Alt|Shift", chars = "\u001bN" },
#mcbpro   { key = "O",         mods = "Alt|Shift", chars = "\u001bO" },
#mcbpro   { key = "P",         mods = "Alt|Shift", chars = "\u001bP" },
#mcbpro   { key = "Q",         mods = "Alt|Shift", chars = "\u001bQ" },
#mcbpro   { key = "R",         mods = "Alt|Shift", chars = "\u001bR" },
#mcbpro   { key = "S",         mods = "Alt|Shift", chars = "\u001bS" },
#mcbpro   { key = "T",         mods = "Alt|Shift", chars = "\u001bT" },
#mcbpro   { key = "U",         mods = "Alt|Shift", chars = "\u001bU" },
#mcbpro   { key = "V",         mods = "Alt|Shift", chars = "\u001bV" },
#mcbpro   { key = "W",         mods = "Alt|Shift", chars = "\u001bW" },
#mcbpro   { key = "X",         mods = "Alt|Shift", chars = "\u001bX" },
#mcbpro   { key = "Y",         mods = "Alt|Shift", chars = "\u001bY" },
#mcbpro   { key = "Z",         mods = "Alt|Shift", chars = "\u001bZ" },
#mcbpro   { key = "Key1",      mods = "Alt",       chars = "\u001b1" },
#mcbpro   { key = "Key2",      mods = "Alt",       chars = "\u001b2" },
#mcbpro   { key = "Key3",      mods = "Alt",       chars = "\u001b3" },
#mcbpro   { key = "Key4",      mods = "Alt",       chars = "\u001b4" },
#mcbpro   { key = "Key5",      mods = "Alt",       chars = "\u001b5" },
#mcbpro   { key = "Key6",      mods = "Alt",       chars = "\u001b6" },
#mcbpro   { key = "Key7",      mods = "Alt",       chars = "\u001b7" },
#mcbpro   { key = "Key8",      mods = "Alt",       chars = "\u001b8" },
#mcbpro   { key = "Key9",      mods = "Alt",       chars = "\u001b9" },
#mcbpro   { key = "Key0",      mods = "Alt",       chars = "\u001b0" },
#mcbpro   { key = "Space",     mods = "Control",   chars = "\u0000"  },
#mcbpro   { key = "Period",    mods = "Alt",       chars = "\u001b." },
#mcbpro   { key = "Key8",      mods = "Alt|Shift", chars = "\u001b*" },
#mcbpro   { key = "Key3",      mods = "Alt|Shift", chars = "\u001b#" },
#mcbpro   { key = "Period",    mods = "Alt|Shift", chars = "\u001b>" },
#mcbpro   { key = "Comma",     mods = "Alt|Shift", chars = "\u001b<" },
#mcbpro   { key = "Minus",     mods = "Alt|Shift", chars = "\u001b_" },
#mcbpro   { key = "Key5",      mods = "Alt|Shift", chars = "\u001b%" },
#mcbpro   { key = "Key6",      mods = "Alt|Shift", chars = "\u001b^" },
#mcbpro   { key = "Backslash", mods = "Alt",       chars = "\u001b\\"},
#mcbpro   { key = "Backslash", mods = "Alt|Shift", chars = "\u001b|" },
#mcbpro ]
