# Linux Darwin
# https://raw.githubusercontent.com/aarowill/base16-alacritty/master/colors/base16-brewer-256.yml
# Base16 Brewer 256 - alacritty color config
# Timothée Poisot (http://github.com/tpoisot)
colors:
  # Default colors
  primary:
    background: '0x0c0d0e'
    foreground: '0xa3a3a3'

  cursor:
#carbon    cursor: '0xf81ce5'
#macbookpro     ursor: '0xffffff'
   # cursor: '0xcbccc6'
   # cursor: '0xffa759' #orange

  # Normal colors
  normal:
    black:   '0x0c0d0e'
    red:     '0xe31a1c'
    green:   '0x31a354'
    yellow:  '0xdca060'
    blue:    '0x3182bd'
    magenta: '0x756bb1'
    cyan:    '0x80b1d3'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x737475'
    red:     '0xe31a1c'
    green:   '0x31a354'
    yellow:  '0xdca060'
    blue:    '0x3182bd'
    magenta: '0x756bb1'
    cyan:    '0x80b1d3'
    white:   '0xfcfdfe'

## custom
window:
#macbookpro   decorations: None
  title: alacritty
  dynamic_title: true
  class:
    instance: alacritty
    general: alacritty

font:
#carbon   size: 11.0
#macbookpro   size: 14.0
  normal:
    family: Source Code Pro
#carbon     style: regular

#macbookpro key_bindings:
#macbookpro   - { key: A,         mods: Alt,       chars: "\x1ba"                       }
#macbookpro   - { key: B,         mods: Alt,       chars: "\x1bb"                       }
#macbookpro   - { key: C,         mods: Alt,       chars: "\x1bc"                       }
#macbookpro   - { key: D,         mods: Alt,       chars: "\x1bd"                       }
#macbookpro   - { key: E,         mods: Alt,       chars: "\x1be"                       }
#macbookpro   - { key: F,         mods: Alt,       chars: "\x1bf"                       }
#macbookpro   - { key: G,         mods: Alt,       chars: "\x1bg"                       }
#macbookpro   - { key: H,         mods: Alt,       chars: "\x1bh"                       }
#macbookpro   - { key: I,         mods: Alt,       chars: "\x1bi"                       }
#macbookpro   - { key: J,         mods: Alt,       chars: "\x1bj"                       }
#macbookpro   - { key: K,         mods: Alt,       chars: "\x1bk"                       }
#macbookpro   - { key: L,         mods: Alt,       chars: "\x1bl"                       }
#macbookpro   - { key: M,         mods: Alt,       chars: "\x1bm"                       }
#macbookpro   - { key: N,         mods: Alt,       chars: "\x1bn"                       }
#macbookpro   - { key: O,         mods: Alt,       chars: "\x1bo"                       }
#macbookpro   - { key: P,         mods: Alt,       chars: "\x1bp"                       }
#macbookpro   - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
#macbookpro   - { key: R,         mods: Alt,       chars: "\x1br"                       }
#macbookpro   - { key: S,         mods: Alt,       chars: "\x1bs"                       }
#macbookpro   - { key: T,         mods: Alt,       chars: "\x1bt"                       }
#macbookpro   - { key: U,         mods: Alt,       chars: "\x1bu"                       }
#macbookpro   - { key: V,         mods: Alt,       chars: "\x1bv"                       }
#macbookpro   - { key: W,         mods: Alt,       chars: "\x1bw"                       }
#macbookpro   - { key: X,         mods: Alt,       chars: "\x1bx"                       }
#macbookpro   - { key: Y,         mods: Alt,       chars: "\x1by"                       }
#macbookpro   - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
#macbookpro   - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
#macbookpro   - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
#macbookpro   - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
#macbookpro   - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
#macbookpro   - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
#macbookpro   - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
#macbookpro   - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
#macbookpro   - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
#macbookpro   - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
#macbookpro   - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
#macbookpro   - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
#macbookpro   - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
#macbookpro   - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
#macbookpro   - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
#macbookpro   - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
#macbookpro   - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
#macbookpro   - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
#macbookpro   - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
#macbookpro   - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
#macbookpro   - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
#macbookpro   - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
#macbookpro   - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
#macbookpro   - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
#macbookpro   - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
#macbookpro   - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
#macbookpro   - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
#macbookpro   - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
#macbookpro   - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
#macbookpro   - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
#macbookpro   - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
#macbookpro   - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
#macbookpro   - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
#macbookpro   - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
#macbookpro   - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
#macbookpro   - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
#macbookpro   - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
#macbookpro   - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
#macbookpro   - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
#macbookpro   - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
#macbookpro   - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
#macbookpro   - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
#macbookpro   - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
#macbookpro   - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
#macbookpro   - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
#macbookpro   - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
#macbookpro   - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
#macbookpro   - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
#macbookpro   - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
#macbookpro   - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |
