# Linux Darwin
# https://raw.githubusercontent.com/aarowill/base16-alacritty/master/colors/base16-brewer-256.yml
# Base16 Brewer 256 - alacritty color config
# Timothée Poisot (http://github.com/tpoisot)
colors:
  # Default colors
  primary:
    background: '0x0c0d0e'
    foreground: '0xbbbbbb'

  cursor:
#carbon    cursor: '0xf81ce5'
#macbookpro     ursor: '0xffffff'
   # cursor: '0xcbccc6'
   # cursor: '0xffa759' #orange

  # Normal colors
  normal:
    black:   '0x0c0d0e'
    red:     '0xe31a1c'
    green:   '0x31a354'
    yellow:  '0xdca060'
    blue:    '0x3182bd'
    magenta: '0x756bb1'
    cyan:    '0x80b1d3'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x737475'
    red:     '0xe31a1c'
    green:   '0x31a354'
    yellow:  '0xdca060'
    blue:    '0x3182bd'
    magenta: '0x756bb1'
    cyan:    '0x80b1d3'
    white:   '0xfcfdfe'

## custom
window:
  title: alacritty
  dynamic_title: true
  class:
    instance: alacritty
    general: alacritty

font:
#carbon   size: 11.0
#macbookpro   size: 14.0
  normal:
    family: Source Code Pro
#carbon     style: regular
