# Linux Darwin

window:
  decorations: None
  title: alacritty
  dynamic_title: true
  class:
    instance: alacritty
    general: alacritty

font:
#carbon   size: 11.0
#mcbpro   size: 14.0
  normal:
    family: SF Mono
#carbon     style: regular

#mcbpro key_bindings:
#mcbpro   - { key: A,         mods: Alt,       chars: "\x1ba"                       }
#mcbpro   - { key: B,         mods: Alt,       chars: "\x1bb"                       }
#mcbpro   - { key: C,         mods: Alt,       chars: "\x1bc"                       }
#mcbpro   - { key: D,         mods: Alt,       chars: "\x1bd"                       }
#mcbpro   - { key: E,         mods: Alt,       chars: "\x1be"                       }
#mcbpro   - { key: F,         mods: Alt,       chars: "\x1bf"                       }
#mcbpro   - { key: G,         mods: Alt,       chars: "\x1bg"                       }
#mcbpro   - { key: H,         mods: Alt,       chars: "\x1bh"                       }
#mcbpro   - { key: I,         mods: Alt,       chars: "\x1bi"                       }
#mcbpro   - { key: J,         mods: Alt,       chars: "\x1bj"                       }
#mcbpro   - { key: K,         mods: Alt,       chars: "\x1bk"                       }
#mcbpro   - { key: L,         mods: Alt,       chars: "\x1bl"                       }
#mcbpro   - { key: M,         mods: Alt,       chars: "\x1bm"                       }
#mcbpro   - { key: N,         mods: Alt,       chars: "\x1bn"                       }
#mcbpro   - { key: O,         mods: Alt,       chars: "\x1bo"                       }
#mcbpro   - { key: P,         mods: Alt,       chars: "\x1bp"                       }
#mcbpro   - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
#mcbpro   - { key: R,         mods: Alt,       chars: "\x1br"                       }
#mcbpro   - { key: S,         mods: Alt,       chars: "\x1bs"                       }
#mcbpro   - { key: T,         mods: Alt,       chars: "\x1bt"                       }
#mcbpro   - { key: U,         mods: Alt,       chars: "\x1bu"                       }
#mcbpro   - { key: V,         mods: Alt,       chars: "\x1bv"                       }
#mcbpro   - { key: W,         mods: Alt,       chars: "\x1bw"                       }
#mcbpro   - { key: X,         mods: Alt,       chars: "\x1bx"                       }
#mcbpro   - { key: Y,         mods: Alt,       chars: "\x1by"                       }
#mcbpro   - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
#mcbpro   - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
#mcbpro   - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
#mcbpro   - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
#mcbpro   - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
#mcbpro   - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
#mcbpro   - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
#mcbpro   - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
#mcbpro   - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
#mcbpro   - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
#mcbpro   - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
#mcbpro   - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
#mcbpro   - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
#mcbpro   - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
#mcbpro   - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
#mcbpro   - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
#mcbpro   - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
#mcbpro   - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
#mcbpro   - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
#mcbpro   - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
#mcbpro   - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
#mcbpro   - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
#mcbpro   - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
#mcbpro   - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
#mcbpro   - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
#mcbpro   - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
#mcbpro   - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
#mcbpro   - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
#mcbpro   - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
#mcbpro   - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
#mcbpro   - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
#mcbpro   - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
#mcbpro   - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
#mcbpro   - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
#mcbpro   - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
#mcbpro   - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
#mcbpro   - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
#mcbpro   - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
#mcbpro   - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
#mcbpro   - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
#mcbpro   - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
#mcbpro   - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
#mcbpro   - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
#mcbpro   - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
#mcbpro   - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
#mcbpro   - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
#mcbpro   - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
#mcbpro   - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
#mcbpro   - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
#mcbpro   - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |


# https://gist.githubusercontent.com/sainnhe/ad5cbc4f05c4ced83f80e54d9a75d22f/raw/939021739051393ceff88d3df014fb5e4e90e7aa/gruvbox-material-alacritty.yml
schemes:
  gruvbox_material_hard_dark: &gruvbox_material_hard_dark
    primary:
      background: '0x1d2021'
      foreground: '0xd4be98'
    normal:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_medium_dark: &gruvbox_material_medium_dark
    primary:
      background: '0x282828'
      foreground: '0xd4be98'
    normal:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_soft_dark: &gruvbox_material_soft_dark
    primary:
      background: '0x32302f'
      foreground: '0xd4be98'
    normal:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_hard_light: &gruvbox_material_hard_light
    primary:
      background: '0xf9f5d7'
      foreground: '0x654735'
    normal:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xf2e5bc'
    bright:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xf2e5bc'
  gruvbox_material_medium_light: &gruvbox_material_medium_light
    primary:
      background: '0xfbf1c7'
      foreground: '0x654735'
    normal:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xeee0b7'
    bright:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xeee0b7'
  gruvbox_material_soft_light: &gruvbox_material_soft_light
    primary:
      background: '0xf2e5bc'
      foreground: '0x654735'
    normal:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xe6d5ae'
    bright:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xe6d5ae'

# https://raw.githubusercontent.com/projekt0n/github-theme-contrib/main/themes/alacritty/github_dark_dimmed.yml 
  github_dark_dimmed: &github_dark_dimmed
    colors:
      primary:
        background: '0x22272e'
        foreground: '0xadbac7'
      cursor:
        text: '0x22272e'
        cursor: '0xadbac7'
      normal:
        black: '0x545d68'
        red: '0xf47067'
        green: '0x57ab5a'
        yellow: '0xc69026'
        blue: '0x539bf5'
        magenta: '0xb083f0'
        cyan: '0x39c5cf'
        white: '0x909dab'
      bright:
        black: '0x636e7b'
        red: '0xff938a'
        green: '0x6bc46d'
        yellow: '0xdaaa3f'
        blue: '0x6cb6ff'
        magenta: '0xb083f0'
        cyan: '0x39c5cf'
        white: '0x909dab'

# https://raw.githubusercontent.com/aarowill/base16-alacritty/master/colors/base16-brewer-256.yml
  base16-brewer-256: &base16-brewer-256
    primary:
      background: '0x0c0d0e'
      foreground: '0xa3a3a3'
    cursor:
      cursor: '0xf81ce5'
    normal:
      black:   '0x0c0d0e'
      red:     '0xe31a1c'
      green:   '0x31a354'
      yellow:  '0xdca060'
      blue:    '0x3182bd'
      magenta: '0x756bb1'
      cyan:    '0x80b1d3'
      white:   '0xffffff'
    bright:
      black:   '0x737475'
      red:     '0xe31a1c'
      green:   '0x31a354'
      yellow:  '0xdca060'
      blue:    '0x3182bd'
      magenta: '0x756bb1'
      cyan:    '0x80b1d3'
      white:   '0xfcfdfe'

# Apply the color scheme.
colors: *github_dark_dimmed
