# Linux Darwin
window:
  decorations: None
  title: alacritty
  dynamic_title: true
  class:
    instance: alacritty
    general: alacritty

font:
#carbon   size: 11.0
#mcbpro   size: 14.0
  normal:
    family: SF Mono
#carbon     style: regular

#mcbpro key_bindings:
#mcbpro   - { key: A,         mods: Alt,       chars: "\x1ba"                       }
#mcbpro   - { key: B,         mods: Alt,       chars: "\x1bb"                       }
#mcbpro   - { key: C,         mods: Alt,       chars: "\x1bc"                       }
#mcbpro   - { key: D,         mods: Alt,       chars: "\x1bd"                       }
#mcbpro   - { key: E,         mods: Alt,       chars: "\x1be"                       }
#mcbpro   - { key: F,         mods: Alt,       chars: "\x1bf"                       }
#mcbpro   - { key: G,         mods: Alt,       chars: "\x1bg"                       }
#mcbpro   - { key: H,         mods: Alt,       chars: "\x1bh"                       }
#mcbpro   - { key: I,         mods: Alt,       chars: "\x1bi"                       }
#mcbpro   - { key: J,         mods: Alt,       chars: "\x1bj"                       }
#mcbpro   - { key: K,         mods: Alt,       chars: "\x1bk"                       }
#mcbpro   - { key: L,         mods: Alt,       chars: "\x1bl"                       }
#mcbpro   - { key: M,         mods: Alt,       chars: "\x1bm"                       }
#mcbpro   - { key: N,         mods: Alt,       chars: "\x1bn"                       }
#mcbpro   - { key: O,         mods: Alt,       chars: "\x1bo"                       }
#mcbpro   - { key: P,         mods: Alt,       chars: "\x1bp"                       }
#mcbpro   - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
#mcbpro   - { key: R,         mods: Alt,       chars: "\x1br"                       }
#mcbpro   - { key: S,         mods: Alt,       chars: "\x1bs"                       }
#mcbpro   - { key: T,         mods: Alt,       chars: "\x1bt"                       }
#mcbpro   - { key: U,         mods: Alt,       chars: "\x1bu"                       }
#mcbpro   - { key: V,         mods: Alt,       chars: "\x1bv"                       }
#mcbpro   - { key: W,         mods: Alt,       chars: "\x1bw"                       }
#mcbpro   - { key: X,         mods: Alt,       chars: "\x1bx"                       }
#mcbpro   - { key: Y,         mods: Alt,       chars: "\x1by"                       }
#mcbpro   - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
#mcbpro   - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
#mcbpro   - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
#mcbpro   - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
#mcbpro   - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
#mcbpro   - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
#mcbpro   - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
#mcbpro   - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
#mcbpro   - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
#mcbpro   - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
#mcbpro   - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
#mcbpro   - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
#mcbpro   - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
#mcbpro   - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
#mcbpro   - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
#mcbpro   - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
#mcbpro   - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
#mcbpro   - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
#mcbpro   - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
#mcbpro   - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
#mcbpro   - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
#mcbpro   - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
#mcbpro   - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
#mcbpro   - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
#mcbpro   - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
#mcbpro   - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
#mcbpro   - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
#mcbpro   - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
#mcbpro   - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
#mcbpro   - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
#mcbpro   - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
#mcbpro   - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
#mcbpro   - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
#mcbpro   - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
#mcbpro   - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
#mcbpro   - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
#mcbpro   - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
#mcbpro   - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
#mcbpro   - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
#mcbpro   - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
#mcbpro   - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
#mcbpro   - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
#mcbpro   - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
#mcbpro   - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
#mcbpro   - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
#mcbpro   - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
#mcbpro   - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
#mcbpro   - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
#mcbpro   - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
#mcbpro   - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |


#base16_vim_partnerlook
colors: #base16_vim_partnerlook
  primary: #base16_vim_partnerlook
    background: '0x0f1419' #base16_vim_partnerlook
    foreground: '0xe6e1cf' #base16_vim_partnerlook
  cursor: #base16_vim_partnerlook
    text:       '0x0f1419' #base16_vim_partnerlook
    cursor:     '0xe6e1cf' #base16_vim_partnerlook
  normal: #base16_vim_partnerlook
    black:      '0x0f1419' #base16_vim_partnerlook
    red:        '0xf07178' #base16_vim_partnerlook
    green:      '0xb8cc52' #base16_vim_partnerlook
    yellow:     '0xffb454' #base16_vim_partnerlook
    blue:       '0x59c2ff' #base16_vim_partnerlook
    magenta:    '0xd2a6ff' #base16_vim_partnerlook
    cyan:       '0x95e6cb' #base16_vim_partnerlook
    white:      '0xe6e1cf' #base16_vim_partnerlook
  bright: #base16_vim_partnerlook
    black:      '0x3e4b59' #base16_vim_partnerlook
    red:        '0xf07178' #base16_vim_partnerlook
    green:      '0xb8cc52' #base16_vim_partnerlook
    yellow:     '0xffb454' #base16_vim_partnerlook
    blue:       '0x59c2ff' #base16_vim_partnerlook
    magenta:    '0xd2a6ff' #base16_vim_partnerlook
    cyan:       '0x95e6cb' #base16_vim_partnerlook
    white:      '0xf3f4f5' #base16_vim_partnerlook
