# vim: set ft=tmux tw=0 nowrap:
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g base-index 1
setw -g pane-base-index 1

set -sg escape-time 0
set -g mouse on
set -g focus-events on

setw -g mode-keys vi
bind -n C-a send-prefix
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key / copy-mode \; send-key ?

bind-key u run-shell -b 'tmux capture-pane -p | xurls | sort | uniq | fzf --tmux -1 | xargs -t -I{} xdg-open {} > /dev/null || true'
bind-key U run-shell -b 'tmux capture-pane -p | fzf --tmux=bottom --reverse | xurls | xargs -t -I{} xdg-open {} > /dev/null || true'
bind-key m attach-session -c "#{pane_current_path}" \; rename-session "#{pane_current_path}"

bind = select-layout even-horizontal
bind - select-layout tiled

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

primary="#333333"
secondary="#aaaaaa"
accent="#{{base09-hex}}"
#accent="#{{base0A-hex}}" #black-metal
white="#ffffff"

set -g status-style "bg=$primary fg=$secondary"
set -g message-command-style "bg=$accent fg=$primary bold"
set -g message-style "bg=$accent fg=$primary bold"
set -g mode-style "bg=$secondary fg=$primary"
set -g pane-border-style "fg=$primary"
set -g pane-active-border-style "fg=$secondary"
set -g window-status-current-style "fg=$white bold"
set -g window-status-style "bg=$primary fg=$secondary"
set -g clock-mode-colour "$accent"
set -g display-panes-active-colour "$accent"
set -g display-panes-colour "$secondary"

set-option -g status-left "#[bold]#S | "
set-option -g status-left-length 1024
set-option -g status-right "#{?client_prefix,#[bold]#[fg=$accent]C-b#[nobold]#[fg=default],} #[bold]#(tmux capture-pane -p -t spotify_player | awk -F'▶' '/▶/ {print $2}' | head -1 | sed 's/[[:space:]][[:space:]]//g;s/│/ /g' )#(tmux capture-pane -p -t radio | awk -F':' '/icy-title:/ {print $2}' | tail -1 )#[nobold] | %Y-%m-%d #[bold]#[fg=$white]%H:%M#[nobold]#[fg=default] [kw:%V|%j|%s]"
set-option -g status-right-length 1024
