git_protocol: ssh
aliases:
  checks: >-
    !gh pr checks --json 'name,link,state' \
      | fx 'x => x.map(xx => [xx.state.padEnd(8), xx.link.padEnd(72), xx.name].join("\t")).join("\n")' \
      | sort -r \
      | awk '1 {print $0 > "/dev/stderr";} /^FAILURE/{print $2 > "/dev/stdout";}' \
      | xurls \
      | xargs xdg-open

  prs: >-
    !gh api graphql -f query="
        {
          search(query: \"type:pr state:${GH_PR_STATE:-open} sort:created-desc involves:@me archived:false\", type: ISSUE, first: 20) {
            edges { node { ... on PullRequest { title url createdAt author { ... on User {login} } } } }
          }
        }" \
        | fx 'x => x.data.search.edges.map(xx => [xx.node.createdAt, xx.node.url.padEnd(48), xx.node.author.login.padEnd(32), xx.node.title.substring(0,96)].join("\t")).join("\n")' \
        | fzf --reverse --preview-window=bottom --preview 'gh pr view {2}' \
        | xurls \
        | xargs -t -I{} gh pr ${*:-view} {}

  get: >-
    !
    case "$1" in
     fzf)
      mkdir -p $HOME/.fzf/plugin 2>/dev/null
      tag_name=$(gh release list --limit 1 --repo junegunn/fzf --json tagName --jq '.[].tagName')
      printf "tag_name=%s\n" $tag_name
#carbon      gh release download $tag_name --repo junegunn/fzf --pattern '*linux_amd64*'  --output - | tar xvz -C "$HOME/.fzf/"
#mcbpro      gh release download $tag_name --repo junegunn/fzf --pattern '*darwin_arm64*' --output - | tar xvz -C "$HOME/.fzf/"
      curl -LSs "https://github.com/junegunn/fzf/blob/$tag_name/shell/completion.zsh?raw=true"           --output "$HOME/.fzf/completion.zsh"
      curl -LSs "https://github.com/junegunn/fzf/blob/$tag_name/shell/key-bindings.zsh?raw=true"         --output "$HOME/.fzf/key-bindings.zsh"
      curl -LSs "https://github.com/junegunn/fzf/blob/$tag_name/plugin/fzf.vim?raw=true"                 --output "$HOME/.fzf/plugin/fzf.vim"
      fzf --version
     ;;

     nvim)
       rm -rf $HOME/.nvim/* 2>/dev/null || mkdir -p $HOME/.nvim/ 2>/dev/null
#carbon       curl https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz -L     | tar xvz -C $HOME/.nvim/
#mcbpro       curl https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz -L | tar xvz -C $HOME/.nvim/
       nvim --version
     ;;

     hcloud)
        mkdir -p $HOME/.hcloud 2>/dev/null
        gh release download --repo hetznercloud/cli --pattern '*linux-amd64*'  --output - | tar xvz -C "$HOME/.hcloud/"
     ;;

     bun)
        repo="oven-sh/bun"
        target="${2:-$HOME/.bun}"
#carbon        pattern='bun-linux-x64'

        mkdir -p $target 2>/dev/null
        gh release --repo ${repo} download --pattern "${pattern}.zip" --output - | bsdtar xvz -C "$target"
        chmod +x "$target/$pattern/bun"
     ;;

     *)
       echo "unknown project: $1"
     ;;
    esac
