git_protocol: ssh
aliases:
  checks: >-
      !gh pr checks --json 'name,link,state' \
          | fx 'x => x.map(xx => [xx.state.padEnd(8), xx.link.padEnd(72), xx.name].join("\t")).join("\n")' \
          | sort -r \
          | awk '1 {print $0 > "/dev/stderr";} /^FAILURE/{print $2 > "/dev/stdout";}' \
          | xurls \
          | xargs xdg-open

  prs: >-
    !gh api graphql -f query="
        {
          search(query: \"type:pr state:${GH_PR_STATE:-open} sort:created-desc involves:@me archived:false\", type: ISSUE, first: 20) {
            edges { node { ... on PullRequest { title url createdAt author { ... on User {login} } } } }
          }
        }" \
        | fx 'x => x.data.search.edges.map(xx => [xx.node.createdAt, xx.node.url.padEnd(48), xx.node.author.login.padEnd(32), xx.node.title.substring(0,96)].join("\t")).join("\n")' \
        | fzf --reverse --preview-window=bottom --preview 'gh pr view {2}' \
        | xurls \
        | xargs -t -I{} gh pr ${*:-view} {}

  get: >-
    !
    case "$1" in
     hcloud)
        mkdir -p $HOME/.hcloud 2>/dev/null
        gh release download --repo hetznercloud/cli --pattern '*linux-amd64*'  --output - | tar xvz -C "$HOME/.hcloud/"
     ;;

     bun)
        repo="oven-sh/bun"
        target="${2:-$HOME/.bun}"
#carbon        pattern='bun-linux-x64'

        mkdir -p $target 2>/dev/null
        gh release --repo ${repo} download --pattern "${pattern}.zip" --output - | bsdtar xvz -C "$target"
        chmod +x "$target/$pattern/bun"
     ;;

     *)
       echo "unknown project: $1"
     ;;
    esac
