[buffer]
cookie = false
images = false
scripting = false
styling = true

[display]
image-mode = "none"
color-mode = "ansi"

[external]
copy-cmd = "xclip -i -rmlastnl -selection clipboard"
paste-cmd = "xclip -o -selection clipboard"
mailcap = [
  "~/.config/chawan/mailcap"
]

[page]
C-k = "() => pager.load('ddg:')"
' f' = "pager.externFilterSource('fmt')"
' r' = "pager.externFilterSource('rdrview -Hu \"$CHA_URL\"')"

[[siteconf]]
url = '^https://hup.hu/.*'
styling = false

[[siteconf]]
url = '^https://news.ycombinator.com/.*'
styling = true
color-mode = "true-color"
