[buffer]
cookie = false
images = false
scripting = false
styling = true

[display]
image-mode = "none"
color-mode = "auto"

[external]
copy-cmd = "xclip -i -rmlastnl -selection clipboard"
paste-cmd = "xclip -o -selection clipboard"
mailcap = [
  "~/.config/chawan/mailcap"
]

[page]
C-k = "() => pager.load('ddg:')"
' f' = "pager.externFilterSource('fmt')"
' r' = "pager.externFilterSource('rdrview -T url,title,body -H \"$CHA_URL\"')"
' d' = "pager.externFilterSource('reader \"$CHA_URL\" --raw')"
o = "cmd.pager.loadEmpty"

[[siteconf]]
url = '^https://hup.hu/.*'
styling = false

[[siteconf]]
url = '^https://news.ycombinator.com/.*'
styling = true

[[siteconf]]
url = '^https://(www\.|[^old]\.)?reddit\.com/.*'
rewrite-url = 'x => { x.host = "redlib.catsarch.com" }'

[[siteconf]]
url = '^https://x\.com/.*'
rewrite-url = 'x => { x.host = "xcancel.com" }'

[[siteconf]]
url = '^https://github.com/.*/blob/'
rewrite-url = 'x => { x.search = "raw=true" }'
