config.load_autoconfig();

c.url.searchengines = {
    'DEFAULT':  'https://start.duckduckgo.com/html/?q={}',
    '!d':       'https://start.duckduckgo.com/?q={}',
    '!dw':      'https://thefreedictionary.com/{}',
    '!gh':      'https://github.com/search?o=desc&q={}&s=stars',
    '!gist':    'https://gist.github.com/search?q={}',
    '!r':       'https://old.reddit.com/search?q={}',
    '!w':       'https://en.wikipedia.org/wiki/{}',
    '!yt':      'https://www.youtube.com/results?search_query={}'
}

config.bind(',m', 'hint links spawn --detach mpv {hint-url} --ytdl-raw-options=format-sort="res:720" --pause --cache-pause-initial=yes')

#mcbpro c.fonts.completion.category = '15pt'
#mcbpro c.fonts.completion.entry = '15pt'
#mcbpro c.fonts.debug_console = '15pt'
#mcbpro c.fonts.downloads = '15pt'
#mcbpro c.fonts.hints = '15pt'
#mcbpro c.fonts.keyhint = '15pt'
#mcbpro c.fonts.messages.error = '15pt'
#mcbpro c.fonts.messages.info = '15pt'
#mcbpro c.fonts.messages.warning = '15pt'
#mcbpro c.fonts.prompts = '15pt'
#mcbpro c.fonts.statusbar = '15pt'
#mcbpro c.fonts.tabs.selected = '15pt'
#mcbpro c.fonts.tabs.unselected = '15pt'
#mbcpro c.qt.highdpi = true
#mcbpro c.fonts.default_family = "GeistMono Nerd Font"

# origin: https://github.com/theova/base16-qutebrowser
#mcbpro c.colors.completion.fg = "#{{base05-hex}}"
#mcbpro c.colors.completion.odd.bg = "#{{base01-hex}}"
#mcbpro c.colors.completion.even.bg = "#{{base00-hex}}"
#mcbpro c.colors.completion.category.fg = "#{{base0A-hex}}"
#mcbpro c.colors.completion.category.bg = "#{{base00-hex}}"
#mcbpro c.colors.completion.category.border.top = "#{{base00-hex}}"
#mcbpro c.colors.completion.category.border.bottom = "#{{base00-hex}}"
#mcbpro c.colors.completion.item.selected.fg = "#{{base05-hex}}"
#mcbpro c.colors.completion.item.selected.bg = "#{{base02-hex}}"
#mcbpro c.colors.completion.item.selected.border.top = "#{{base02-hex}}"
#mcbpro c.colors.completion.item.selected.border.bottom = "#{{base02-hex}}"
#mcbpro c.colors.completion.item.selected.match.fg = "#{{base0B-hex}}"
#mcbpro c.colors.completion.match.fg = "#{{base0B-hex}}"
#mcbpro c.colors.completion.scrollbar.fg = "#{{base05-hex}}"
#mcbpro c.colors.completion.scrollbar.bg = "#{{base00-hex}}"
#mcbpro c.colors.contextmenu.disabled.bg = "#{{base01-hex}}"
#mcbpro c.colors.contextmenu.disabled.fg = "#{{base04-hex}}"
#mcbpro c.colors.contextmenu.menu.bg = "#{{base00-hex}}"
#mcbpro c.colors.contextmenu.menu.fg =  "#{{base05-hex}}"
#mcbpro c.colors.contextmenu.selected.bg = "#{{base02-hex}}"
#mcbpro c.colors.contextmenu.selected.fg = "#{{base05-hex}}"
#mcbpro c.colors.downloads.bar.bg = "#{{base00-hex}}"
#mcbpro c.colors.downloads.start.fg = "#{{base00-hex}}"
#mcbpro c.colors.downloads.start.bg = "#{{base0D-hex}}"
#mcbpro c.colors.downloads.stop.fg = "#{{base00-hex}}"
#mcbpro c.colors.downloads.stop.bg = "#{{base0C-hex}}"
#mcbpro c.colors.downloads.error.fg = "#{{base08-hex}}"
#mcbpro c.colors.hints.fg = "#{{base00-hex}}"
#mcbpro c.colors.hints.bg = "#{{base0A-hex}}"
#mcbpro c.colors.hints.match.fg = "#{{base05-hex}}"
#mcbpro c.colors.keyhint.fg = "#{{base05-hex}}"
#mcbpro c.colors.keyhint.suffix.fg = "#{{base05-hex}}"
#mcbpro c.colors.keyhint.bg = "#{{base00-hex}}"
#mcbpro c.colors.messages.error.fg = "#{{base00-hex}}"
#mcbpro c.colors.messages.error.bg = "#{{base08-hex}}"
#mcbpro c.colors.messages.error.border = "#{{base08-hex}}"
#mcbpro c.colors.messages.warning.fg = "#{{base00-hex}}"
#mcbpro c.colors.messages.warning.bg = "#{{base0E-hex}}"
#mcbpro c.colors.messages.warning.border = "#{{base0E-hex}}"
#mcbpro c.colors.messages.info.fg = "#{{base05-hex}}"
#mcbpro c.colors.messages.info.bg = "#{{base00-hex}}"
#mcbpro c.colors.messages.info.border = "#{{base00-hex}}"
#mcbpro c.colors.prompts.fg = "#{{base05-hex}}"
#mcbpro c.colors.prompts.border = "#{{base00-hex}}"
#mcbpro c.colors.prompts.bg = "#{{base00-hex}}"
#mcbpro c.colors.prompts.selected.bg = "#{{base02-hex}}"
#mcbpro c.colors.prompts.selected.fg = "#{{base05-hex}}"
#mcbpro c.colors.statusbar.normal.fg = "#{{base0B-hex}}"
#mcbpro c.colors.statusbar.normal.bg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.insert.fg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.insert.bg = "#{{base0D-hex}}"
#mcbpro c.colors.statusbar.passthrough.fg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.passthrough.bg = "#{{base0C-hex}}"
#mcbpro c.colors.statusbar.private.fg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.private.bg = "#{{base01-hex}}"
#mcbpro c.colors.statusbar.command.fg = "#{{base05-hex}}"
#mcbpro c.colors.statusbar.command.bg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.command.private.fg = "#{{base05-hex}}"
#mcbpro c.colors.statusbar.command.private.bg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.caret.fg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.caret.bg = "#{{base0E-hex}}"
#mcbpro c.colors.statusbar.caret.selection.fg = "#{{base00-hex}}"
#mcbpro c.colors.statusbar.caret.selection.bg = "#{{base0D-hex}}"
#mcbpro c.colors.statusbar.progress.bg = "#{{base0D-hex}}"
#mcbpro c.colors.statusbar.url.fg = "#{{base05-hex}}"
#mcbpro c.colors.statusbar.url.error.fg = "#{{base08-hex}}"
#mcbpro c.colors.statusbar.url.hover.fg = "#{{base05-hex}}"
#mcbpro c.colors.statusbar.url.success.http.fg = "#{{base0C-hex}}"
#mcbpro c.colors.statusbar.url.success.https.fg = "#{{base0B-hex}}"
#mcbpro c.colors.statusbar.url.warn.fg = "#{{base0E-hex}}"
#mcbpro c.colors.tabs.bar.bg = "#{{base00-hex}}"
#mcbpro c.colors.tabs.indicator.start = "#{{base0D-hex}}"
#mcbpro c.colors.tabs.indicator.stop = "#{{base0C-hex}}"
#mcbpro c.colors.tabs.indicator.error = "#{{base08-hex}}"
#mcbpro c.colors.tabs.odd.fg = "#{{base05-hex}}"
#mcbpro c.colors.tabs.odd.bg = "#{{base01-hex}}"
#mcbpro c.colors.tabs.even.fg = "#{{base05-hex}}"
#mcbpro c.colors.tabs.even.bg = "#{{base00-hex}}"
#mcbpro c.colors.tabs.pinned.even.bg = "#{{base0C-hex}}"
#mcbpro c.colors.tabs.pinned.even.fg = "#{{base07-hex}}"
#mcbpro c.colors.tabs.pinned.odd.bg = "#{{base0B-hex}}"
#mcbpro c.colors.tabs.pinned.odd.fg = "#{{base07-hex}}"
#mcbpro c.colors.tabs.pinned.selected.even.bg = "#{{base02-hex}}"
#mcbpro c.colors.tabs.pinned.selected.even.fg = "#{{base05-hex}}"
#mcbpro c.colors.tabs.pinned.selected.odd.bg = "#{{base02-hex}}"
#mcbpro c.colors.tabs.pinned.selected.odd.fg = "#{{base05-hex}}"
#mcbpro c.colors.tabs.selected.odd.fg = "#{{base05-hex}}"
#mcbpro c.colors.tabs.selected.odd.bg = "#{{base02-hex}}"
#mcbpro c.colors.tabs.selected.even.fg = "#{{base05-hex}}"
#mcbpro c.colors.tabs.selected.even.bg = "#{{base02-hex}}"
#mcbpro # c.colors.webpage.bg = "#{{base00-hex}}"
