vim.cmd("hi clear|syntax reset")
vim.g.colors_name = "custom"

vim.api.nvim_set_hl(0, 'Bold', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Boolean', { fg = '#{{base0A-hex}}' })
vim.api.nvim_set_hl(0, 'Boolean', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Character', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'ColorColumn', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Comment', { fg = '#{{base03-hex}}' })
vim.api.nvim_set_hl(0, 'Comment', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Conceal', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Conditional', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'CursorColumn', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'CursorLine', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Debug', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Define', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInformation', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarning', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffAdded', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffFile', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffLine', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffNewFile', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffRemoved', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'DiffText', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Error', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Exception', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Float', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'FoldColumn', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Folded', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#{{base07-hex}}' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'IncSearch',{ bg = '#{{base0A-hex}}', fg = '#{{base00-hex}}' })
vim.api.nvim_set_hl(0, 'Include', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Italic', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Label', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#{{base02-hex}}' })
vim.api.nvim_set_hl(0, 'LspInlayHint', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'LspReferenceText', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Macro', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'MatchParen', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'MiniCompletionActiveParameter', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Normal', { fg = '#{{base05-hex}}' })
vim.api.nvim_set_hl(0, 'Normal', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#{{base06-hex}}' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'NvimInternalError', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#{{base05-hex}}' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'PMenu', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'PMenuSel', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Repeat', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Search',{ bg = '#{{base0A-hex}}', fg = '#{{base00-hex}}' })
vim.api.nvim_set_hl(0, 'SignColumn', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#{{base05-hex}}' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'SpecialChar', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'SpellBad', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'SpellCap', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'SpellLocal', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'SpellRare', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#{{base0A-hex}}' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#{{base0B-hex}}' })
vim.api.nvim_set_hl(0, 'StorageClass', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'String', { fg = '#{{base07-hex}}' })
vim.api.nvim_set_hl(0, 'String', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Structure', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Substitute', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSAnnotation', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSAttribute', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSBoolean', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSCharacter', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSComment', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSConditional', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSConstBuiltin', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSConstMacro', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSConstant', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSConstructor', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSCurrentScope', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSDefinition', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSDefinitionUsage', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSEmphasis', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSError', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSException', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSField', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSFloat', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSFuncBuiltin', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSFuncMacro', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSFunction', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSInclude', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSKeyword', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSKeywordFunction', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSKeywordOperator', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSLabel', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSLiteral', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSMethod', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSNamespace', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSNone', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSNumber', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSOperator', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSParameter', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSParameterReference', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSProperty', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSPunctBracket', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSPunctDelimiter', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSPunctSpecial', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSRepeat', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSStrike', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSString', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSStringEscape', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSStringRegex', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSStrong', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSSymbol', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSTag', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSTagDelimiter', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSText', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSTitle', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSType', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSTypeBuiltin', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSURI', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSUnderline', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSVariable', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TSVariableBuiltin', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TabLineFill', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TermCursor', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TermCursorNC', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Todo', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TooLong', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'TreesitterContext', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Typedef', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Underlined', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#{{base09-hex}}', fg = '#{{base00-hex}}' })
vim.api.nvim_set_hl(0, 'VisualNOS', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'WildMenu', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'WinBar', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'WinBarNC', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitBranch', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitComment', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitDiscarded', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitDiscardedFile', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitDiscardedType', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitHeader', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitOverflow', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitSelected', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitSelectedFile', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitSelectedType', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitSummary', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitUnmergedFile', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitUnmergedType', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitUntracked', { fg = '#{{base04-hex}}' })
vim.api.nvim_set_hl(0, 'gitcommitUntrackedFile', { fg = '#{{base04-hex}}' })


-- if vim.fn.has('nvim-0.8.0') then
--     hi['@comment']                  = 'TSComment'
--     hi['@error']                    = 'TSError'
--     hi['@none']                     = 'TSNone'
--     hi['@preproc']                  = 'PreProc'
--     hi['@define']                   = 'Define'
--     hi['@operator']                 = 'TSOperator'
--     hi['@punctuation.delimiter']    = 'TSPunctDelimiter'
--     hi['@punctuation.bracket']      = 'TSPunctBracket'
--     hi['@punctuation.special']      = 'TSPunctSpecial'
--     hi['@string']                   = 'TSString'
--     hi['@string.regex']             = 'TSStringRegex'
--     hi['@string.escape']            = 'TSStringEscape'
--     hi['@string.special']           = 'SpecialChar'
--     hi['@character']                = 'TSCharacter'
--     hi['@character.special']        = 'SpecialChar'
--     hi['@boolean']                  = 'TSBoolean'
--     hi['@number']                   = 'TSNumber'
--     hi['@float']                    = 'TSFloat'
--     hi['@function']                 = 'TSFunction'
--     hi['@function.call']            = 'TSFunction'
--     hi['@function.builtin']         = 'TSFuncBuiltin'
--     hi['@function.macro']           = 'TSFuncMacro'
--     hi['@method']                   = 'TSMethod'
--     hi['@method.call']              = 'TSMethod'
--     hi['@constructor']              = 'TSConstructor'
--     hi['@parameter']                = 'TSParameter'
--     hi['@keyword']                  = 'TSKeyword'
--     hi['@keyword.function']         = 'TSKeywordFunction'
--     hi['@keyword.operator']         = 'TSKeywordOperator'
--     hi['@keyword.return']           = 'TSKeyword'
--     hi['@conditional']              = 'TSConditional'
--     hi['@repeat']                   = 'TSRepeat'
--     hi['@debug']                    = 'Debug'
--     hi['@label']                    = 'TSLabel'
--     hi['@include']                  = 'TSInclude'
--     hi['@exception']                = 'TSException'
--     hi['@type']                     = 'TSType'
--     hi['@type.builtin']             = 'TSTypeBuiltin'
--     hi['@type.qualifier']           = 'TSKeyword'
--     hi['@type.definition']          = 'TSType'
--     hi['@storageclass']             = 'StorageClass'
--     hi['@attribute']                = 'TSAttribute'
--     hi['@field']                    = 'TSField'
--     hi['@property']                 = 'TSProperty'
--     hi['@variable']                 = 'TSVariable'
--     hi['@variable.builtin']         = 'TSVariableBuiltin'
--     hi['@constant']                 = 'TSConstant'
--     hi['@constant.builtin']         = 'TSConstant'
--     hi['@constant.macro']           = 'TSConstant'
--     hi['@namespace']                = 'TSNamespace'
--     hi['@symbol']                   = 'TSSymbol'
--     hi['@text']                     = 'TSText'
--     hi['@text.diff.add']            = 'DiffAdd'
--     hi['@text.diff.delete']         = 'DiffDelete'
--     hi['@text.strong']              = 'TSStrong'
--     hi['@text.emphasis']            = 'TSEmphasis'
--     hi['@text.underline']           = 'TSUnderline'
--     hi['@text.strike']              = 'TSStrike'
--     hi['@text.title']               = 'TSTitle'
--     hi['@text.literal']             = 'TSLiteral'
--     hi['@text.uri']                 = 'TSUri'
--     hi['@text.math']                = 'Number'
--     hi['@text.environment']         = 'Macro'
--     hi['@text.environment.name']    = 'Type'
--     hi['@text.reference']           = 'TSParameterReference'
--     hi['@text.todo']                = 'Todo'
--     hi['@text.note']                = 'Tag'
--     hi['@text.warning']             = 'DiagnosticWarn'
--     hi['@text.danger']              = 'DiagnosticError'
--     hi['@tag']                      = 'TSTag'
--     hi['@tag.attribute']            = 'TSAttribute'
--     hi['@tag.delimiter']            = 'TSTagDelimiter'
--     hi['@function.method']          = '@method'
--     hi['@function.method.call']     = '@method.call'
--     hi['@comment.error']            = '@text.danger'
--     hi['@comment.warning']          = '@text.warning'
--     hi['@comment.hint']             = 'DiagnosticHint'
--     hi['@comment.info']             = 'DiagnosticInfo'
--     hi['@comment.todo']             = '@text.todo'
--     hi['@diff.plus']                = '@text.diff.add'
--     hi['@diff.minus']               = '@text.diff.delete'
--     hi['@diff.delta']               = 'DiffChange'
--     hi['@string.special.url']       = '@text.uri'
--     hi['@keyword.directive']        = '@preproc'
--     hi['@keyword.directive.define'] = '@define'
--     hi['@keyword.storage']          = '@storageclass'
--     hi['@keyword.conditional']      = '@conditional'
--     hi['@keyword.debug']            = '@debug'
--     hi['@keyword.exception']        = '@exception'
--     hi['@keyword.import']           = '@include'
--     hi['@keyword.repeat']           = '@repeat'
--     hi['@variable.parameter']       = '@parameter'
--     hi['@variable.member']          = '@field'
--     hi['@module']                   = '@namespace'
--     hi['@number.float']             = '@float'
--     hi['@string.special.symbol']    = '@symbol'
--     hi['@string.regexp']            = '@string.regex'
--     hi['@markup.strong']            = '@text.strong'
--     hi['@markup.italic']            = '@text.italic'
--     hi['@markup.link']              = '@text.link'
--     hi['@markup.strikethrough']     = '@text.strikethrough'
--     hi['@markup.heading']           = '@text.title'
--     hi['@markup.raw']               = '@text.literal'
--     hi['@markup.link']              = '@text.reference'
--     hi['@markup.link.url']          = '@text.uri'
--     hi['@markup.link.label']        = '@string.special'
--     hi['@markup.list']              = '@punctuation.special'
-- end
-- if M.config.lsp_semantic then
--     hi['@class'] = 'TSType'
--     hi['@struct'] = 'TSType'
--     hi['@enum'] = 'TSType'
--     hi['@enumMember'] = 'Constant'
--     hi['@event'] = 'Identifier'
--     hi['@interface'] = 'Structure'
--     hi['@modifier'] = 'Identifier'
--     hi['@regexp'] = 'TSStringRegex'
--     hi['@typeParameter'] = 'Type'
--     hi['@decorator'] = 'Identifier'
--
--     hi['@lsp.type.namespace'] = '@namespace'
--     hi['@lsp.type.type'] = '@type'
--     hi['@lsp.type.class'] = '@type'
--     hi['@lsp.type.enum'] = '@type'
--     hi['@lsp.type.interface'] = '@type'
--     hi['@lsp.type.struct'] = '@type'
--     hi['@lsp.type.parameter'] = '@parameter'
--     hi['@lsp.type.variable'] = '@variable'
--     hi['@lsp.type.property'] = '@property'
--     hi['@lsp.type.enumMember'] = '@constant'
--     hi['@lsp.type.function'] = '@function'
--     hi['@lsp.type.method'] = '@method'
--     hi['@lsp.type.macro'] = '@function.macro'
--     hi['@lsp.type.decorator'] = '@function'
-- end
