statusbar_format = "> %artists - %title >"

[theme]
title = "#{{base09-hex}}"
highlight = "#{{base05-hex}}"
highlight_bg = "#{{base00-hex}}"
playing = "#{{base05-hex}}"
playing_selected = "#{{base05-hex}}"
playing_bg = "#{{base00-hex}}"
statusbar_progress = "#{{base09-hex}}"
statusbar_format = "%artists - %title"
cmdline_bg = "#{{base09-hex}}"
# vim: ft=cfg
