# vim: ft=cfg
statusbar_format = "> %artists - %title >"

[theme]
statusbar_format = "%artists - %title"

title = "#{{base09-hex}}"
# statusbar_progress = "#{{base09-hex}}"
# cmdline_bg = "#{{base09-hex}}"
# highlight = "#{{base00-hex}}"
# highlight_bg = "#{{base09-hex}}"
# playing = "#{{base09-hex}}"
# highlight = "#{{base00-hex}}"
# highlight_bg = "#{{base09-hex}}"
# playing = "#{{base09-hex}}"
#
