# vim: ft=cfg
statusbar_format = "> %artists - %title >"

[theme]
background = "transparent"
primary = "#{{base05-hex}}"
secondary = "transparent"
title = "#{{base09-hex}}"
playing = "#{{base0C-hex}}"
playing_selected = "#{{base09-hex}}"
playing_bg = "transparent"
highlight = "#{{base09-hex}}"
highlight_bg = "black"
error = "light white"
error_bg = "red"
statusbar = "transparent"
statusbar_progress = "#{{base09-hex}}"
statusbar_bg = "transparent"
cmdline = "black"
cmdline_bg = "${{base09-hex}"
search_match = "#{{base0A-hex}}"
